- name: Add Repository
  lineinfile:
      path: /etc/apt/sources.list.d/wazuh.list
      line: 'deb https://packages.wazuh.com/4.x/apt/ stable main'
      state: present
      mode: 0440
      create: yes
- name: Debian/Ubuntu | Installing Wazuh repository key
  become: true
  shell: |
    set -o pipefail
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
  args:
    warn: false
    executable: /bin/bash
- name: Update
  become: true
  apt: 
    update_cache: yes
- name: wait
  pause:
    minutes: 5
- name: Install Wazuh-agent
  become: true
  command: "WAZUH_MANAGER=sherlock apt-get install wazuh-agent"
- name: daemon-reload
  become: true
  command: "systemctl daemon-reload"
- name: enable wazuh
  become: true
  command: "systemctl enable wazuh-agent"
- name: start wazuh
  become: true
  command: "systemctl start wazuh-agent"