- name: Install ClamAV packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - clamav
    - clamav-base
    - clamav-daemon
    - clamav-freshclam 
  register: pkg_result
  until: pkg_result is success


