---
- name: modifyTemplate
  community.general.proxmox_kvm:
     api_host: "{{ api_host }}"
     api_user: "{{ api_user }}" 
     api_token_id: "{{ api_token_id }}"
     api_token_secret: "{{ api_token_secret }}"
     name: WinMaster
     node: cosasdecasa
     cores: "{{ cores }}"
     memory: "{{ memory }}"
     update: yes
  tags: template

- name: Clone VM   
  community.general.proxmox_kvm:
     api_host: "{{ api_host }}"
     api_user: "{{ api_user }}" 
     api_token_id: "{{ api_token_id }}"
     api_token_secret: "{{ api_token_secret }}"
     clone: loquesea
     vmid: 100      
     newid: "{{ new_id }}"
     name: "{{ win_machine }}"
     node: cosasdecasa
     format: unspecified
     full: yes
     tags: tfm
     timeout: 1200
  tags: create_windows

- name: Start VM
  community.general.proxmox_kvm:
     api_host: "{{ api_host }}"
     api_user: "{{ api_user }}" 
     api_token_id: "{{ api_token_id }}"
     api_token_secret: "{{ api_token_secret }}"
     vmid: "{{ new_id }}"
     node: cosasdecasa
     state: started
  tags: start_linux
  

  





  











