---

    - name: check if sysmon archive is present
      win_stat:
        path: c:\Program Files\sysmon\sysmon
      register: sysmondl

    - name: download sysmon
      win_get_url:
        url: "{{ win_sysmon_url }}"
        dest: 'c:\Program Files\sysmon\{{ win_sysmon_url | basename }}'
        timeout: 60
      when: not sysmondl.stat.exists

    - name: unzip sysmon
      win_unzip:
        src: 'c:\Program Files\sysmon\{{ win_sysmon_url | basename }}'
        dest: 'c:\Program Files\sysmon\sysmon'
        creates: 'c:\Program Files\sysmon\sysmon\sysmon.exe'
      when: not sysmondl.stat.exists

    - name: add sysmon to PATH
      win_path:
        elements: 'c:\Program Files\sysmon\sysmon'
      when: not sysmondl.stat.exists

    - name: Copy Sysmon template
      win_template:
        src: "SysmonConfig-TSwift.xml.j2"
        dest: 'c:\Program Files\sysmon\SysmonConfig-TSwift.xml'

    - name: install sysmon with defined config
      win_command: '"c:\Program Files\sysmon\sysmon\sysmon64.exe" -accepteula -i "c:\Program Files\sysmon\SysmonConfig-TSwift.xml"'

