
- name: Change the hostname to new_hostname
  hosts: WinMaster
  tasks:
    - name: change hostname
      win_hostname:
        name: WinMaster
      register: win_hostname

    - name: Reboot
      win_reboot:
      when: win_hostname.reboot_required