- name: Install ClamAV packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - epel-release
    - clamav
    - clamav-update
    - clamav-scanner-systemd



